development: &common_settings
  cluster_name: "Aces"
  dashboard_url: "http://127.0.0.1:5000"
  file_app_url: "/pun/sys/files/fs"
  file_editor_url: "/pun/sys/file-editor/edit"
  home_page: "https://hprc.tamu.edu"
  request_email: "help@hprc.tamu.edu"
  help_email: "help@hprc.tamu.edu"
  modules_db_path: "/sw/hprc/sw/portal_utils/modules.sqlite3"
  driver_scripts_path: "/var/www/ood/apps/dev/u.sv309862/dor-hprc-HPCMosaic-dev/machine_driver_scripts"
  tamubatch_path: "/sw/local/bin/tamubatch"
  default_matlab_module: "Matlab/R2020b"
  hprcbot_route: 'http://courant.hprc.tamu.edu:8553'
  default_python_venv: "/sw/hprc/sw/Python/virtualenvs/Python/3.8.6/default_dashboard_python-env/"
  send_result_path: "/var/www/ood/apps/dev/u.sv309862/dor-hprc-HPCMosaic-dev/machine_driver_scripts/send_result.sh"

production:
  <<: *common_settings
  dashboard_url: "/pun/sys/dor-hprc-HPCMosaic-dev"
  request_email: "help@hprc.tamu.edu"
  driver_scripts_path: "/var/www/ood/apps/sys/dor-hprc-HPCMosaic-dev/machine_driver_scripts"
  send_result_path: "/var/www/ood/apps/sys/dor-hprc-HPCMosaic-dev/machine_driver_scripts/send_result.sh"
  help_email: "help@hprc.tamu.edu"
